<?php
/**
 * Autoloader definition for eZ Publish Extension files.
 *
 * @copyright Copyright (C) 1999-2010 eZ Systems AS. All rights reserved.
 * @license http://ez.no/licenses/gnu_gpl GNU General Public License v2.0
 * @version 4.4.0
 * @package kernel
 *
 */

return array(
      'EnchantSpell'                      => 'extension/ezoe/modules/ezoe/classes/EnchantSpell.php',
      'GoogleSpell'                       => 'extension/ezoe/modules/ezoe/classes/GoogleSpell.php',
      'JSMin'                             => 'extension/ezjscore/lib/jsmin.php',
      'JSMinException'                    => 'extension/ezjscore/lib/jsmin.php',
      'Moxiecode_JSON'                    => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'Moxiecode_JSONReader'              => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'PSpell'                            => 'extension/ezoe/modules/ezoe/classes/PSpell.php',
      'PSpellShell'                       => 'extension/ezoe/modules/ezoe/classes/PSpellShell.php',
      'SpellChecker'                      => 'extension/ezoe/modules/ezoe/classes/SpellChecker.php',
      'eZArchive'                         => 'extension/ezwebin/autoloads/ezarchive.php',
      'eZContentClassEditDeferredHandler' => 'extension/ezscriptmonitor/classes/ezcontentclasseditdeferredhandler.php',
      'eZCreateClassListGroups'           => 'extension/ezwt/autoloads/ezcreateclasslistgroups.php',
      'eZFeedReader'                      => 'extension/ezflow/autoloads/ezfeedreader.php',
      'eZFlowAjaxContent'                 => 'extension/ezflow/classes/ezflowajaxcontent.php',
      'eZFlowBlock'                       => 'extension/ezflow/classes/ezflowblock.php',
      'eZFlowFetchInterface'              => 'extension/ezflow/classes/ezflowfetchinterface.php',
      'eZFlowFunctionCollection'          => 'extension/ezflow/modules/ezflow/functioncollection.php',
      'eZFlowKeywordsFetch'               => 'extension/ezflow/classes/fetches/ezflowkeywordsfetch.php',
      'eZFlowLatestContent'               => 'extension/ezflow/classes/fetches/ezflowlatestcontent.php',
      'eZFlowLatestObjects'               => 'extension/ezflow/classes/fetches/ezflowlatestobjects.php',
      'eZFlowMCFetch'                     => 'extension/ezflow/classes/fetches/ezflowmcfetch.php',
      'eZFlowOperations'                  => 'extension/ezflow/classes/ezflowoperations.php',
      'eZFlowPool'                        => 'extension/ezflow/classes/ezflowpool.php',
      'eZFlowPoolItem'                    => 'extension/ezflow/classes/ezflowpoolitem.php',
      'eZFlowServerCallFunctions'         => 'extension/ezflow/classes/ezflowservercallfunctions.php',
      'eZGmapLocation'                    => 'extension/ezgmaplocation/classes/ezgmaplocation.php',
      'eZGmapLocationInfo'                => 'extension/ezgmaplocation/ezinfo.php',
      'eZGmapLocationType'                => 'extension/ezgmaplocation/datatypes/ezgmaplocation/ezgmaplocationtype.php',
      'eZHTTPCacheManager'                => 'extension/ezflow/classes/ezhttpcachemanager.php',
      'eZHTTPCacheManagerInterface'       => 'extension/ezflow/classes/ezhttpcachemanagerinterface.php',
      'eZIEEzcConversions'                => 'extension/ezie/classes/interfaces/conversions.php',
      'eZIEEzcGDHandler'                  => 'extension/ezie/classes/handlers/gd.php',
      'eZIEEzcImageMagickHandler'         => 'extension/ezie/classes/handlers/magick.php',
      'eZIEImageAction'                   => 'extension/ezie/classes/image_action.php',
      'eZIEImageAnalyzer'                 => 'extension/ezie/classes/image_analyzer.php',
      'eZIEImageFilterBW'                 => 'extension/ezie/classes/image_filter_bw.php',
      'eZIEImageFilterBrightness'         => 'extension/ezie/classes/image_filter_brightness.php',
      'eZIEImageFilterContrast'           => 'extension/ezie/classes/image_filter_contrast.php',
      'eZIEImageFilterSepia'              => 'extension/ezie/classes/image_filter_sepia.php',
      'eZIEImagePreAction'                => 'extension/ezie/classes/image_pre_action.php',
      'eZIEImageToolCrop'                 => 'extension/ezie/classes/image_tool_crop.php',
      'eZIEImageToolFlipHorizontally'     => 'extension/ezie/classes/image_tool_flip_horizontally.php',
      'eZIEImageToolFlipVertically'       => 'extension/ezie/classes/image_tool_flip_vertically.php',
      'eZIEImageToolPixelate'             => 'extension/ezie/classes/image_tool_pixelate.php',
      'eZIEImageToolResize'               => 'extension/ezie/classes/image_tool_resize.php',
      'eZIEImageToolRotation'             => 'extension/ezie/classes/image_tool_rotation.php',
      'eZIEImageToolWatermark'            => 'extension/ezie/classes/image_tool_watermark.php',
      'eZIEezcImageConverter'             => 'extension/ezie/classes/image_converter.php',
      'eZJSON'                            => 'extension/ezflow/autoloads/ezjson.php',
      'eZKeywordList'                     => 'extension/ezwebin/autoloads/ezkeywordlist.php',
      'eZOEInputParser'                   => 'extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php',
      'eZOETemplateUtils'                 => 'extension/ezoe/autoloads/ezoetemplateutils.php',
      'eZOEXMLInput'                      => 'extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php',
      'eZOOConverter'                     => 'extension/ezodf/classes/ezooconverter.php',
      'eZOOGenerator'                     => 'extension/ezodf/classes/ezoogenerator.php',
      'eZOOImport'                        => 'extension/ezodf/classes/ezooimport.php',
      'eZOpenofficeUploadHandler'         => 'extension/ezodf/uploadhandlers/ezopenofficeuploadhandler.php',
      'eZPage'                            => 'extension/ezflow/classes/ezpage.php',
      'eZPageBlock'                       => 'extension/ezflow/classes/ezpageblock.php',
      'eZPageBlockItem'                   => 'extension/ezflow/classes/ezpageblockitem.php',
      'eZPageData'                        => 'extension/ezwebin/autoloads/ezpagedata.php',
      'eZPageType'                        => 'extension/ezflow/datatypes/ezpage/ezpagetype.php',
      'eZPageZone'                        => 'extension/ezflow/classes/ezpagezone.php',
      'eZRESTODFHandler'                  => 'extension/ezodf/classes/ezrestodfhandler.php',
      'eZRed5StreamListOperator'          => 'extension/ezflow/autoloads/ezred5streamlist.php',
      'eZScheduledScript'                 => 'extension/ezscriptmonitor/classes/ezscheduledscript.php',
      'eZScriptMonitorInfo'               => 'extension/ezscriptmonitor/ezinfo.php',
      'eZSquidCacheManager'               => 'extension/ezflow/classes/ezsquidcachemanager.php',
      'eZStarRatingInfo'                  => 'extension/ezstarrating/ezinfo.php',
      'eZTagCloud'                        => 'extension/ezwebin/autoloads/eztagcloud.php',
      'eZUnserialize'                     => 'extension/ezflow/autoloads/ezunserialize.php',
      'ezflowInfo'                        => 'extension/ezflow/ezinfo.php',
      'ezgmlLocationFilter'               => 'extension/ezgmaplocation/classes/ezgmllocationfilter.php',
      'ezjscAccessTemplateFunctions'      => 'extension/ezjscore/autoloads/ezjscaccesstemplatefunctions.php',
      'ezjscAjaxContent'                  => 'extension/ezjscore/classes/ezjscajaxcontent.php',
      'ezjscEncodingTemplateFunctions'    => 'extension/ezjscore/autoloads/ezjscencodingtemplatefunctions.php',
      'ezjscPacker'                       => 'extension/ezjscore/classes/ezjscpacker.php',
      'ezjscPackerTemplateFunctions'      => 'extension/ezjscore/autoloads/ezjscpackertemplatefunctions.php',
      'ezjscServerFunctions'              => 'extension/ezjscore/classes/ezjscserverfunctions.php',
      'ezjscServerFunctionsJs'            => 'extension/ezjscore/classes/ezjscserverfunctionsjs.php',
      'ezjscServerFunctionsNode'          => 'extension/ezjscore/classes/ezjscserverfunctionsnode.php',
      'ezjscServerRouter'                 => 'extension/ezjscore/classes/ezjscserverrouter.php',
      'ezjscoreInfo'                      => 'extension/ezjscore/ezinfo.php',
      'ezodfInfo'                         => 'extension/ezodf/ezinfo.php',
      'ezoeInfo'                          => 'extension/ezoe/ezinfo.php',
      'ezoeServerFunctions'               => 'extension/ezoe/classes/ezoeserverfunctions.php',
      'ezsrRatingDataObject'              => 'extension/ezstarrating/classes/ezsrratingdataobject.php',
      'ezsrRatingFilter'                  => 'extension/ezstarrating/classes/ezsrratingfilter.php',
      'ezsrRatingObject'                  => 'extension/ezstarrating/classes/ezsrratingobject.php',
      'ezsrRatingObjectTreeNode'          => 'extension/ezstarrating/classes/ezsrratingobjecttreenode.php',
      'ezsrRatingType'                    => 'extension/ezstarrating/datatypes/ezsrrating/ezsrratingtype.php',
      'ezsrServerFunctions'               => 'extension/ezstarrating/classes/ezsrserverfunctions.php',
      'ezsrTemplateOperators'             => 'extension/ezstarrating/autoloads/ezsrtemplateoperators.php',
      'ezwebinInfo'                       => 'extension/ezwebin/ezinfo.php',
      'ezwtInfo'                          => 'extension/ezwt/ezinfo.php',
      'ezwtServerCallFunctions'           => 'extension/ezwt/classes/ezwtservercallfunctions.php',
    );

?>
